# Imagen base de Python (puedes usar 3.10 o 3.12; elijo 3.12 para que coincida contigo)
FROM python:3.12-slim

# Establecer directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar requirements e instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar TODO el proyecto (api.py, ingest.py, models/, etc.)
COPY . .

# Comando para levantar la API
# api:app  => archivo api.py, objeto app
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "80"]